---
title: Thriving Mindsets
tagline: The pursuit of growth is a game played between you and yourself
description: The pursuit of growth is a game played between you and yourself
url: http://thrivingmindsets.org
baseurl: ''
author:
  name: Andrew Fong
  url: https://twitter.com/fongandrewc
paginate: 5
exclude:
- README.md
- vendor/bundle
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
sidebar_home_link: true
theme_colors:
  sidebar-bg-color: "#000000"
  sidebar-fg-color: "#FFFFFF"
  link-color: "#000000"
sidebar-sticky: true
layout-reverse: false
remote_theme: fongandrew/hydeout
google_analytics: ''
disqus:
  shortname: ''
theme: jekyll-theme-hydeout
markdown: ''
highlighter: ''
