---
title: Thriving Mindsets
tagline: ''
description: ''
url: https://thrivingmindsets.org
baseurl: ''
author:
  name: Luke Butler
  url: https://twitter.com/lukebutler
paginate: 5
exclude:
- README.md
- vendor/bundle
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
sidebar_home_link: true
theme_colors:
  sidebar-bg-color: "#000000"
  sidebar-fg-color: "#FFFFFF"
  link-color: "#000000"
sidebar-sticky: true
layout-reverse: false
remote_theme: fongandrew/hydeout
google_analytics: UA-168015479-1
disqus:
  shortname: ''
theme: jekyll-theme-hydeout
